# Site settings.

title: ChordPro
baseURL: https://www.chordpro.org/beta/
languageCode: en-GB

# Build properties.

#relativeURLs: "true"

disableKinds:
- taxonomy
- RSS
- sitemap

enableRobotsTXT: "true"

# Allow ChordPro specific environment variables.
security:
  funcs:
    getenv: [ "^CHORDPRO_" ]

################ Parameters ################

params:

  author: Johan Vromans
  description: Create beautiful lead sheets
  email: info@chordpro.org
  keywords: music,chord,chords,chordii,chordpro,typesetting,chopro,cho,crd,guitar,music sheets

  stable: https://www.chordpro.org/chordpro/
  
  link_github: https://github.com/ChordPro/chordpro
  link_paypal: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=WDKWDE6R3KR98&lc=GB&item_name=ChordPro&currency_code=EUR&bn=PP-DonationsBF%3Abtn_donate_LG.gif%3ANonHosted
  link_coffee: https://ko-fi.com/chordpro

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true

