name: Full Build on macOS (ARM)

# Open a new branch 'macosbuild' and push this workflow to it.
# Maybe adjust the version as well.
#
# git checkout -b macosbuild
# edit lib/ChordPro/Version.pm
# git commit --no-verify -m "Force macOS build." lib/ChordPro/Version.pm
# git push --set-upstream origin macosbuild
#
# git checkout dev
# git branch -D macosbuild
# git push origin :macosbuild

on:
  push:
    branches:
      - macosbuild

env:
  AWV: 0.72
  WXP: 3.009

jobs:

  macARM:
    runs-on: macos-14

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: perl -V
        run: perl -V

      - name: Install cpanm
        run: brew install cpanm

      # Install wxWidgets 3.2.
      # This installs wx-config as wx-config-3.2, so fix that.
      - name: Set up wxWidgets
        run: |
          brew install wxwidgets@3.2
          sudo install `which wx-config-3.2` /usr/local/bin/wx-config

      # No use to proceed if we do not have all wx components.
      - name: Check libraries
        run: perl pp/macos/libtool.pl

      - name: Install SSLeay
        run: |
          cpanm Net::SSLeay --notest

      - name: Install Alien::wxWidgets
        run: |
          curl -o awx.tgz -L https://github.com/sciurius/perl-Alien-wxWidgets/releases/download/R0.71/Alien-wxWidgets-$AWV.tar.gz
          tar xf awx.tgz
          cd Alien-wxWidgets-$AWV
          cpanm --installdeps --notest .
          perl ./Build.PL --wxWidgets-build=0
          perl ./Build
          perl ./Build install
          cd ..
          rm -fr Alien-wsWidgets-$AWV
          wx-config --list
          wx-config --version --release --version-full
          perl -MAlien::wxWidgets -e 'Alien::wxWidgets->libraries(qw(stc media webview propgrid ribbon aui xrc qa html))'

      - name: Install wxPerl
        run: |
          cpanm https://github.com/sciurius/wxPerl/releases/download/R$WXP/Wx-$WXP.tar.gz --notest || ( cat $HOME/.cpanm/build.log; false )

      - name: Install other dependencies
        run: |
          cpanm PAR::Packer HarfBuzz::Shaper
          cpanm --installdeps --notest .

      - name: Run Test suite
        run: |
          prove -l t
          perl script/chordpro.pl --about

      - name: Build DMG
        run: make -C pp/macos

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: Upload_DMG_macOS_ARM
          path: pp/macos/ChordPro*ARM.dmg

